apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mtl-tenant
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BasChimmy/argocd-poc
    targetRevision: mulitenv
    path: mtl
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mtl-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BasChimmy/argocd-poc
    targetRevision: mulitenv
    path: mtl-gateway
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: httpd-app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
