apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BasChimmy/argocd-poc
    targetRevision: multienv
    path: app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://cluster1.minikube.svc
    namespace: nginx-app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpd-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BasChimmy/argocd-poc
    targetRevision: multienv
    path: app2
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://cluster1.minikube.svc
    namespace: httpd-app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
